<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { Plus, Trash2 } from 'lucide-vue-next';

import type { SelectableDnsZone } from '@/api/types';
import { displayDnsName } from '@/utils/certificates';
import { createDelegatedCnameInstructions, createDelegatedDnsAlias, readDnsNameInput, validateOptionalDnsAlias } from '@/utils/dnsNames';

const props = defineProps<{
  selectedZone: SelectableDnsZone | null;
  dnsNames: string[];
  dnsProviderName: string;
}>();

const emit = defineEmits<{
  'add-dns-name': [dnsName: string, dnsProviderName: string];
  'remove-dns-name': [dnsName: string];
  'update-dns-alias': [dnsAlias: string];
}>();

const recordName = ref('');
const dnsNameError = ref('');
const useAutoGeneratedAlias = ref(true);
const customDnsAlias = ref('');
const customAliasError = ref('');

const requestedDnsName = computed(() => readDnsNameInput(recordName.value, 'DNS Name').value || null);
const generatedDnsAlias = computed(() => (props.selectedZone ? createDelegatedDnsAlias(props.dnsNames, props.selectedZone) : ''));
const effectiveDnsAlias = computed(() => (useAutoGeneratedAlias.value ? generatedDnsAlias.value : customDnsAlias.value));
const delegatedCnameInstructions = computed(() => createDelegatedCnameInstructions(props.dnsNames, effectiveDnsAlias.value));

watch(
  () => props.selectedZone,
  () => {
    dnsNameError.value = '';
  },
);

watch(
  () => customDnsAlias.value,
  () => {
    if (customDnsAlias.value.trim()) {
      const validation = validateOptionalDnsAlias(customDnsAlias.value);
      customAliasError.value = validation.message;
    } else {
      customAliasError.value = '';
    }
  },
);

watch(
  effectiveDnsAlias,
  (newAlias) => {
    emit('update-dns-alias', newAlias);
  },
);

function clearDnsNameError(): void {
  dnsNameError.value = '';
}

function addDnsName(): void {
  dnsNameError.value = '';

  if (!props.selectedZone) {
    dnsNameError.value = 'Select a DNS alias zone before adding a DNS name.';
    return;
  }

  const dnsNameValidation = readDnsNameInput(recordName.value, 'DNS Name');

  if (dnsNameValidation.message) {
    dnsNameError.value = dnsNameValidation.message;
    return;
  }

  if (props.dnsNames.some((dnsName) => dnsName.toLowerCase() === dnsNameValidation.value.toLowerCase())) {
    dnsNameError.value = 'This DNS name is already in the certificate.';
    return;
  }

  emit('add-dns-name', dnsNameValidation.value, props.selectedZone.dnsProviderName);
  recordName.value = '';
}
</script>

<template>
  <div class="form-section">
    <label
      class="form-label"
      for="delegated-record-name"
    >DNS Name</label>
    <div class="compound-input compound-input--plain">
      <input
        id="delegated-record-name"
        v-model="recordName"
        type="text"
        placeholder="www.example.com, *.example.com"
        :disabled="!selectedZone"
        :aria-invalid="dnsNameError ? 'true' : 'false'"
        @keydown.enter.prevent="addDnsName"
        @input="clearDnsNameError"
      >
      <button
        class="icon-button"
        type="button"
        :disabled="!selectedZone"
        @click="addDnsName"
      >
        <Plus
          :size="16"
          aria-hidden="true"
        />
        <span>Add</span>
      </button>
    </div>
    <div
      v-if="requestedDnsName"
      class="form-result"
    >
      <span>Requested DNS name</span>
      <strong>{{ displayDnsName(requestedDnsName) }}</strong>
    </div>
    <p
      v-if="dnsNameError"
      class="form-error"
    >
      {{ dnsNameError }}
    </p>
    <div class="dns-list dns-list--editable">
      <span
        v-for="dnsName in dnsNames"
        :key="dnsName"
        class="dns-chip dns-chip--removable"
      >
        {{ displayDnsName(dnsName) }}
        <button
          type="button"
          title="Remove DNS name"
          @click="emit('remove-dns-name', dnsName)"
        >
          <Trash2
            :size="13"
            aria-hidden="true"
          />
        </button>
      </span>
    </div>

    <!-- DNS Alias Configuration -->
    <div v-if="dnsNames.length > 0" class="form-section form-section--inline">
      <label class="toggle-row">
        <input
          v-model="useAutoGeneratedAlias"
          type="checkbox"
        >
        <span>Auto-generate DNS alias</span>
      </label>
    </div>

    <!-- Auto-generated or Custom DNS Alias Display/Input -->
    <div
      v-if="dnsNames.length > 0"
      class="delegated-alias"
    >
      <div v-if="useAutoGeneratedAlias" class="form-result">
        <span>DNS alias</span>
        <strong>{{ displayDnsName(generatedDnsAlias) }}</strong>
      </div>
      <div v-else class="form-section">
        <label
          class="form-label"
          for="custom-dns-alias"
        >Custom DNS Alias</label>
        <input
          id="custom-dns-alias"
          v-model="customDnsAlias"
          type="text"
          placeholder="e.g., acme-validation.example.net"
          :aria-invalid="customAliasError ? 'true' : 'false'"
        >
        <p
          v-if="customAliasError"
          class="form-error"
        >
          {{ customAliasError }}
        </p>
      </div>

      <!-- CNAME Instructions -->
      <div v-if="effectiveDnsAlias && !customAliasError" class="cname-list">
        <div class="cname-instructions-header">
          <span>Create these CNAME records in your primary DNS provider:</span>
        </div>
        <div
          v-for="instruction in delegatedCnameInstructions"
          :key="instruction.source"
          class="cname-row"
        >
          <span>{{ displayDnsName(instruction.source) }}</span>
          <strong>{{ displayDnsName(instruction.target) }}</strong>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.cname-instructions-header {
  font-size: 0.875rem;
  color: var(--text-secondary);
  margin-bottom: 0.5rem;
  font-weight: 500;
}
</style>
